"""enrich habit and habit_log

Revision ID: 64c904275282
Revises: 0cd2ffe4f44d
Create Date: 2026-07-25 02:44:13.226133

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '64c904275282'
down_revision: Union[str, Sequence[str], None] = '0cd2ffe4f44d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('habit', sa.Column('description', sa.Text(), nullable=True))
    # Unlike create_table, add_column does not create the enum type on its
    # own — it must be created explicitly first.
    habit_type_enum = sa.Enum('build', 'break', name='habit_type')
    habit_type_enum.create(op.get_bind(), checkfirst=True)
    op.add_column(
        'habit',
        sa.Column('type', habit_type_enum, nullable=False, server_default='build'),
    )
    op.add_column('habit', sa.Column('target_time', sa.Time(), nullable=True))
    op.add_column('habit_log', sa.Column('duration_minutes', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('habit_log', 'duration_minutes')
    op.drop_column('habit', 'target_time')
    op.drop_column('habit', 'type')
    op.drop_column('habit', 'description')
    # ### end Alembic commands ###
    # drop_column does not drop the named Postgres ENUM type it used
    sa.Enum(name='habit_type').drop(op.get_bind(), checkfirst=True)
