"""add status to project

Revision ID: a7ae17aefe62
Revises: 64c904275282
Create Date: 2026-07-25 03:38:11.166223

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a7ae17aefe62'
down_revision: Union[str, Sequence[str], None] = '64c904275282'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Unlike create_table, add_column does not create the enum type on its
    # own — it must be created explicitly first.
    project_status_enum = sa.Enum('active', 'completed', 'archived', name='project_status')
    project_status_enum.create(op.get_bind(), checkfirst=True)
    op.add_column(
        'project',
        sa.Column('status', project_status_enum, nullable=False, server_default='active'),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project', 'status')
    # ### end Alembic commands ###
    sa.Enum(name='project_status').drop(op.get_bind(), checkfirst=True)
