"""add project_id to task

Revision ID: cecbf31ac619
Revises: 01cf6b0d3f63
Create Date: 2026-07-24 03:49:20.247560

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cecbf31ac619'
down_revision: Union[str, Sequence[str], None] = '01cf6b0d3f63'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('project_id', sa.Integer(), nullable=True))
    op.create_foreign_key('fk_task_project_id_project', 'task', 'project', ['project_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_task_project_id_project', 'task', type_='foreignkey')
    op.drop_column('task', 'project_id')
    # ### end Alembic commands ###
