"""add is_active to habit

Revision ID: ec57e1128832
Revises: a7ae17aefe62
Create Date: 2026-07-25 03:44:02.691319

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ec57e1128832'
down_revision: Union[str, Sequence[str], None] = 'a7ae17aefe62'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'habit', sa.Column('is_active', sa.Boolean(), nullable=False, server_default=sa.true())
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('habit', 'is_active')
    # ### end Alembic commands ###
